[package]
name = "wordtui"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
rand = "0.8.5"
ratatui = "0.29.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
